openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /wallet/:
    get:
      operationId: listWallets
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Wallet'
          description: ''
      tags:
      - wallet
    post:
      operationId: createWallet
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Wallet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Wallet'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Wallet'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Wallet'
          description: ''
      tags:
      - wallet
  /wallet/{id}/:
    get:
      operationId: retrieveWallet
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A UUID string identifying this wallet.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Wallet'
          description: ''
      tags:
      - wallet
    put:
      operationId: updateWallet
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A UUID string identifying this wallet.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Wallet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Wallet'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Wallet'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Wallet'
          description: ''
      tags:
      - wallet
    patch:
      operationId: partialUpdateWallet
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A UUID string identifying this wallet.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Wallet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Wallet'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Wallet'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Wallet'
          description: ''
      tags:
      - wallet
    delete:
      operationId: destroyWallet
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A UUID string identifying this wallet.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - wallet
  /transaction/:
    get:
      operationId: listTransactions
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
          description: ''
      tags:
      - transaction
  /transaction/{id}/:
    get:
      operationId: retrieveTransaction
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this transaction.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
          description: ''
      tags:
      - transaction
  /wallet/{id}/send_money/:
    post:
      operationId: sendMoneyWallet
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A UUID string identifying this wallet.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Wallet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Wallet'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Wallet'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Wallet'
          description: ''
      tags:
      - wallet
components:
  schemas:
    Wallet:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        currency:
          enum:
          - zmw
          type: string
        balance:
          type: number
          readOnly: true
        active:
          type: boolean
        user:
          type: integer
      required:
      - currency
      - user
    Transaction:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        amount:
          type: number
        approved:
          type: boolean
          readOnly: true
        wallet:
          type: string
      required:
      - amount
      - wallet
