# Generated by Django 4.1.5 on 2023-01-12 17:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('zmw', 'ZMW')], max_length=200),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.UUIDField(default=uuid.UUID('deb927fe-e30a-4ad7-bf7a-5f3bc7c03bf7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
