# Generated by Django 4.1.5 on 2023-01-12 17:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallet_currency_alter_wallet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3d06e5c2-2d53-493f-af48-4c8d444c5b90'), editable=False, primary_key=True, serialize=False),
        ),
    ]
