# Generated by Django 4.1.5 on 2023-01-15 12:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_wallet_id_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTransaction',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('tx_ref', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('charged_amount', models.FloatField()),
                ('currency', models.CharField(max_length=200)),
                ('app_fee', models.FloatField()),
                ('merchant_fee', models.FloatField()),
                ('processor_response', models.TextField()),
                ('narration', models.TextField()),
                ('status', models.CharField(max_length=200)),
                ('payment_type', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ef5cae04-09e9-45ee-b642-15749d0d1968'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='extra',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.externaltransaction'),
        ),
    ]
