# Generated by Django 4.1.5 on 2023-01-15 12:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_transaction_tx_ref_alter_externaltransaction_tx_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltransaction',
            name='tx_ref',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_ref',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc91e693-c988-4321-acdc-59c19081600e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
