# Generated by Django 4.1.5 on 2023-01-15 12:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_externaltransaction_tx_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlutterwaveTransfer',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('account_number', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('bank_code', models.CharField(max_length=200)),
                ('fullname', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=200)),
                ('debit_currency', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('fee', models.FloatField()),
                ('status', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=200)),
                ('narration', models.TextField()),
                ('is_approved', models.BooleanField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ExternalTransaction',
            new_name='FlutterwavePayment',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='extra',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_ref',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.UUIDField(default=uuid.UUID('631390bd-15fd-4db0-8a7c-8d489b1b9f79'), editable=False, primary_key=True, serialize=False),
        ),
    ]
