# Generated by Django 4.1.5 on 2023-03-04 02:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_alter_wallet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='antecedent',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_ref',
            field=models.CharField(default=uuid.UUID('f332c221-c2c5-4939-b364-33b72458b44f'), max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet'),
        ),
    ]
